### ISSUE TITLE
Reimplement eduzoo-video

### ISSUE THREAD

**Issue by mmarget** [educationZEN/eduzoo-components#13]
currently, the video template is set up, so you have to go to youtube first, before you can access fullscreen. make it to allow fullscreen directly on the eduZOO page. 
example code for embedding it directly:
<code>&lt;iframe width="560" height="315" src="//www.youtube.com/embed/iMpbIYxKqIM" frameborder="0" allowfullscreen&gt;&lt;/iframe&gt;</code>

**Comment by mmarget** [comment]
by digging into this issue, i realised that allowfullscreen might not be supported by youtube-embed, so this feature has to be rewritten entirely

**Comment by joernweissenborn** [comment]
Since the used youtube embed plugin is deprecated, we will implement it our self.

The implementation should already be prepared to also use different providers like Vimeo or lokal content.
